<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Error handling &#8212; 読書ノート 1.6dev documentation</title>
    <link rel="stylesheet" type="text/css" href="../../_static/pygments.css?v=4f649999" />
    <link rel="stylesheet" type="text/css" href="../../_static/alabaster.css?v=1a9a5cd9" />
    <script data-url_root="../../" id="documentation_options" src="../../_static/documentation_options.js?v=5a6f99c4"></script>
    <script src="../../_static/doctools.js?v=888ff710"></script>
    <script src="../../_static/sphinx_highlight.js?v=4825356b"></script>
    <script src="../../_static/mermaid.js?v=578dbed1"></script>
    <link rel="next" title="Promises, async/await" href="11-async.html" />
    <link rel="prev" title="Classes" href="09-classes.html" />
   
  <link rel="stylesheet" href="../../_static/custom.css" type="text/css" />
  
  
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head><body>
  

    <div class="document">
      <div class="documentwrapper">
              <div class="related top">
                &nbsp;
  <nav id="rellinks">
    <ul>
        <li>
          &larr;
          <a href="09-classes.html" title="Previous document">Classes</a>
        </li>
        <li>
          <a href="11-async.html" title="Next document">Promises, async/await</a>
          &rarr;
        </li>
    </ul>
  </nav>
              </div>
          

          <div class="body" role="main">
            
  <section id="error-handling">
<h1><a class="toc-backref" href="#id2" role="doc-backlink">Error handling</a><a class="headerlink" href="#error-handling" title="Permalink to this heading">¶</a></h1>
<nav class="contents" id="contents">
<p class="topic-title">Contents</p>
<ul class="simple">
<li><p><a class="reference internal" href="#error-handling" id="id2">Error handling</a></p>
<ul>
<li><p><a class="reference internal" href="#error-handling-try-catch" id="id3">Error handling, <code class="docutils literal notranslate"><span class="pre">try</span></code> … <code class="docutils literal notranslate"><span class="pre">catch</span></code></a></p></li>
<li><p><a class="reference internal" href="#custom-errors-extending-error" id="id4">Custom errors, extending Error</a></p></li>
</ul>
</li>
</ul>
</nav>
<section id="error-handling-try-catch">
<h2><a class="toc-backref" href="#id3" role="doc-backlink">Error handling, <code class="docutils literal notranslate"><span class="pre">try</span></code> … <code class="docutils literal notranslate"><span class="pre">catch</span></code></a><a class="headerlink" href="#error-handling-try-catch" title="Permalink to this heading">¶</a></h2>
<p>&lt;<a class="reference external" href="https://javascript.info/try-catch">https://javascript.info/try-catch</a>&gt; のノート。</p>
<p>ここで習う構文を使えば、エラーを捕まえて、スクリプトが死ぬのではなく、より合理的な処理をすることができる。</p>
<section id="the-try-catch-syntax">
<h3>The <code class="docutils literal notranslate"><span class="pre">try</span></code> … <code class="docutils literal notranslate"><span class="pre">catch</span></code> syntax<a class="headerlink" href="#the-try-catch-syntax" title="Permalink to this heading">¶</a></h3>
<p>ほかのプログラミング言語にも似たものがある：</p>
<div class="highlight-javascript notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="c1">// code...</span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">err</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="c1">// error handling</span>
<span class="p">}</span>
</pre></div>
</div>
</section>
<section id="error-object">
<h3>Error object<a class="headerlink" href="#error-object" title="Permalink to this heading">¶</a></h3>
<p>すべての組み込みエラーオブジェクトには次のプロパティーがある：</p>
<table class="docutils align-default">
<thead>
<tr class="row-odd"><th class="head"><p>Property</p></th>
<th class="head"><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">name</span></code></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">&quot;ReferenceError&quot;</span></code> などのエラー名を表す文字列</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">message</span></code></p></td>
<td><p>エラーの詳細を述べる文字列</p></td>
</tr>
</tbody>
</table>
</section>
<section id="optional-catch-binding">
<h3>Optional <code class="docutils literal notranslate"><span class="pre">catch</span></code> binding<a class="headerlink" href="#optional-catch-binding" title="Permalink to this heading">¶</a></h3>
<p><code class="docutils literal notranslate"><span class="pre">catch</span></code> 節でエラーを参照しないつもりならば、次のように書ける：</p>
<div class="highlight-javascript notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="c1">// code...</span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="c1">// error handling</span>
<span class="p">}</span>
</pre></div>
</div>
</section>
<section id="using-try-catch">
<h3>Using <code class="docutils literal notranslate"><span class="pre">try</span></code> … <code class="docutils literal notranslate"><span class="pre">catch</span></code><a class="headerlink" href="#using-try-catch" title="Permalink to this heading">¶</a></h3>
<p>本文では次のコードを例示している。</p>
<div class="highlight-javascript notranslate"><div class="highlight"><pre><span></span><span class="kd">let</span><span class="w"> </span><span class="nx">json</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="s2">&quot;{ bad json }&quot;</span><span class="p">;</span>
<span class="k">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="kd">let</span><span class="w"> </span><span class="nx">user</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nb">JSON</span><span class="p">.</span><span class="nx">parse</span><span class="p">(</span><span class="nx">json</span><span class="p">);</span>
<span class="w">    </span><span class="c1">// ...</span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">err</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;Our apologies, the data has errors, we&#39;ll try to request it one more time.&quot;</span><span class="p">);</span>
<span class="w">    </span><span class="nx">alert</span><span class="p">(</span><span class="nx">err</span><span class="p">.</span><span class="nx">name</span><span class="p">);</span>
<span class="w">    </span><span class="nx">alert</span><span class="p">(</span><span class="nx">err</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>
</div>
<p>ここでの <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節での対応はエラーメッセージを出力するだけの単純なものだ。実際には、新しいネットワークリクエストを送る、訪問者に代替手段を提案する、エラーに関する情報をログ機能に送る、などの処理が考えられる。</p>
</section>
<section id="throwing-our-own-errors">
<h3>Throwing our own errors<a class="headerlink" href="#throwing-our-own-errors" title="Permalink to this heading">¶</a></h3>
<p>アプリケーション固有のエラーを考える。</p>
<section id="throw-operator">
<h4><code class="docutils literal notranslate"><span class="pre">Throw</span></code> operator<a class="headerlink" href="#throw-operator" title="Permalink to this heading">¶</a></h4>
<p>演算子 <code class="docutils literal notranslate"><span class="pre">throw</span></code> はエラーを送出する。オペランドにエラーを表現するオブジェクトをとる。</p>
<p>エラーオブジェクトは何でも送出することができる。組み込みエラーに倣って、
<code class="docutils literal notranslate"><span class="pre">name</span></code> と <code class="docutils literal notranslate"><span class="pre">message</span></code> くらいは持たせるのがいい。</p>
<p>JavaScript には組み込みエラーがたくさんある。状況に合致すればそれらを利用してもいい。</p>
<div class="highlight-javascript notranslate"><div class="highlight"><pre><span></span><span class="kd">let</span><span class="w"> </span><span class="nx">error</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="ow">new</span><span class="w"> </span><span class="ne">Error</span><span class="p">(</span><span class="nx">message</span><span class="p">);</span>
<span class="c1">// or = new SyntaxError(message);</span>
<span class="c1">// or = new ReferenceError(message);</span>
</pre></div>
</div>
<p>これらの組み込みエラーにおいては <code class="docutils literal notranslate"><span class="pre">name</span></code> はコンストラクターの名前となる。</p>
<ul class="simple">
<li><p><code class="docutils literal notranslate"><span class="pre">JSON.parse()</span></code> ででたらめな文字列を渡すと <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code> が送出されることを見る。</p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">JSON.parse()</span></code> が成功し、戻り値のオブジェクトにアプリケーションが期待するプロパティーが含まれていない場合、<code class="docutils literal notranslate"><span class="pre">throw</span></code> 文で固有の例外を送出する。</p></li>
</ul>
<p>どちらのエラーも <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節一つで処理していることに注意する。</p>
</section>
</section>
<section id="rethrowing">
<h3>Rethrowing<a class="headerlink" href="#rethrowing" title="Permalink to this heading">¶</a></h3>
<p><code class="docutils literal notranslate"><span class="pre">catch</span></code> 節ではアプリケーションが処理できるエラーしか扱いたくない。処理できるかを判定するのにエラーオブジェクトをテストする。処理できないエラーは再送出する。</p>
<ul class="simple">
<li><p>ここでは演算子 <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> を使って、エラーの型をテストしている。</p></li>
<li><p>再送出は <code class="docutils literal notranslate"><span class="pre">throw</span></code> 文に捕まえたオブジェクトをそのまま渡すことで行う。</p></li>
</ul>
<p>どの <code class="docutils literal notranslate"><span class="pre">catch</span></code> ブロックにも処理されなかったエラーが最終的に生じると、スクリプトは殺される。</p>
</section>
<section id="try-catch-finally">
<h3><code class="docutils literal notranslate"><span class="pre">try</span></code> … <code class="docutils literal notranslate"><span class="pre">catch</span></code> … <code class="docutils literal notranslate"><span class="pre">finally</span></code><a class="headerlink" href="#try-catch-finally" title="Permalink to this heading">¶</a></h3>
<p>JavaScript にも <code class="docutils literal notranslate"><span class="pre">finally</span></code> 節がある。意味も他のプログラミング言語のそれと同じだ。</p>
<p><code class="docutils literal notranslate"><span class="pre">try</span></code> 節に <code class="docutils literal notranslate"><span class="pre">return</span></code> 文など、ブロック外へ脱出する命令がある場合にも
<code class="docutils literal notranslate"><span class="pre">finally</span></code> 節の内容は脱出直前に実行される。</p>
<p><code class="docutils literal notranslate"><span class="pre">try</span></code> 節と <code class="docutils literal notranslate"><span class="pre">finally</span></code> 節があれば、そのエラー処理での <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節は書かなくても文法的には問題ない。</p>
<p>この記事では <code class="docutils literal notranslate"><span class="pre">finally</span></code> 節で例外を送出するケースについて述べられていない。何か欲しい。</p>
</section>
<section id="global-catch">
<h3>Global <code class="docutils literal notranslate"><span class="pre">catch</span></code><a class="headerlink" href="#global-catch" title="Permalink to this heading">¶</a></h3>
<p>仕様にはないが、環境は最終的にエラーを処理するための機能を用意している。</p>
<ul class="simple">
<li><p>Node.js では <code class="docutils literal notranslate"><span class="pre">process.on(&quot;uncaughtException&quot;)</span></code> がそのために用意されている。</p></li>
<li><p>ブラウザーでは、特別プロパティー <code class="docutils literal notranslate"><span class="pre">window.onerror</span></code> に関数を割り当てて、未処理エラーに対して実行させることができる。</p></li>
</ul>
<p>もっとも、アプリケーションで処理し切れなかったエラーがこの機能で満足に処理できるという場合はまずないだろう。せいぜい確認用だ。</p>
</section>
<section id="tasks">
<h3>Tasks<a class="headerlink" href="#tasks" title="Permalink to this heading">¶</a></h3>
<section id="finally-or-just-the-code">
<h4>Finally or just the code?<a class="headerlink" href="#finally-or-just-the-code" title="Permalink to this heading">¶</a></h4>
<p>もう一つ指摘するとすれば、<code class="docutils literal notranslate"><span class="pre">catch</span></code> 節で再送出する場合の後始末も対応できることか。</p>
</section>
</section>
</section>
<section id="custom-errors-extending-error">
<h2><a class="toc-backref" href="#id4" role="doc-backlink">Custom errors, extending Error</a><a class="headerlink" href="#custom-errors-extending-error" title="Permalink to this heading">¶</a></h2>
<p>&lt;<a class="reference external" href="https://javascript.info/custom-errors">https://javascript.info/custom-errors</a>&gt; のノート。</p>
<p>JavaScript では <code class="docutils literal notranslate"><span class="pre">throw</span></code> を任意のオペランドで使用できる。技術的には、独自のエラークラスは <code class="docutils literal notranslate"><span class="pre">Error</span></code> を継承する必要はない。しかし、継承することでエラーオブジェクトを識別するために <code class="docutils literal notranslate"><span class="pre">obj</span> <span class="pre">instanceof</span> <span class="pre">Error</span></code> を使用することが可能になる。したがって、<code class="docutils literal notranslate"><span class="pre">Error</span></code> を継承するのがよい。</p>
<p>アプリケーションが大きくなると、自ずとエラーが階層化される。例えば
<code class="docutils literal notranslate"><span class="pre">HttpTimeoutError</span></code> は <code class="docutils literal notranslate"><span class="pre">HttpError</span></code> を継承する、という具合だ。</p>
<section id="extending-error">
<h3>Extending <code class="docutils literal notranslate"><span class="pre">Error</span></code><a class="headerlink" href="#extending-error" title="Permalink to this heading">¶</a></h3>
<p>関数 <code class="docutils literal notranslate"><span class="pre">readUser(json)</span></code> を自作する状況で、入力にユーザープロパティーが含まれていない場合のエラーをも自作することを考える。そのエラーの定義は、組み込みエラー
<code class="docutils literal notranslate"><span class="pre">Error</span></code> から継承することにすると、さしあたり次のようなものになる：</p>
<div class="highlight-javascript notranslate"><div class="highlight"><pre><span></span><span class="kd">class</span><span class="w"> </span><span class="nx">ValidationError</span><span class="w"> </span><span class="k">extends</span><span class="w"> </span><span class="ne">Error</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="kr">constructor</span><span class="p">(</span><span class="nx">message</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="k">super</span><span class="p">(</span><span class="nx">message</span><span class="p">);</span>
<span class="w">        </span><span class="k">this</span><span class="p">.</span><span class="nx">name</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="s2">&quot;ValidationError&quot;</span><span class="p">;</span>
<span class="w">    </span><span class="p">}</span>
<span class="p">}</span>
</pre></div>
</div>
<ul class="simple">
<li><p><code class="docutils literal notranslate"><span class="pre">Error</span></code> のコンストラクターは <code class="docutils literal notranslate"><span class="pre">message</span></code> しか受け付けないので、サブクラスで
<code class="docutils literal notranslate"><span class="pre">this.name</span></code> を上書きする。</p></li>
</ul>
<p><code class="docutils literal notranslate"><span class="pre">readUser(json)</span></code> の呼び出し例は次のようになる。他の言語と比べて <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節の書き方が面倒であることに気づく：</p>
<div class="highlight-javascript notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="kd">let</span><span class="w"> </span><span class="nx">user</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nx">readUser</span><span class="p">(</span><span class="s1">&#39;{ &quot;age&quot;: 25 }&#39;</span><span class="p">);</span>
<span class="w">    </span><span class="c1">// ...</span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">err</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">err</span><span class="w"> </span><span class="ow">instanceof</span><span class="w"> </span><span class="nx">ValidationError</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">      </span><span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;Invalid data: &quot;</span><span class="w"> </span><span class="o">+</span><span class="w"> </span><span class="nx">err</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="w">    </span><span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">err</span><span class="w"> </span><span class="ow">instanceof</span><span class="w"> </span><span class="ne">SyntaxError</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">      </span><span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;JSON Syntax Error: &quot;</span><span class="w"> </span><span class="o">+</span><span class="w"> </span><span class="nx">err</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="w">    </span><span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="p">{</span>
<span class="w">      </span><span class="k">throw</span><span class="w"> </span><span class="nx">err</span><span class="p">;</span>
<span class="w">    </span><span class="p">}</span>
<span class="p">}</span>
</pre></div>
</div>
<p>JavaScript の <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節は <code class="docutils literal notranslate"><span class="pre">throw</span></code> されたすべてのエラーを捕捉するため、エラータイプによる場合分けを、上のようにより特殊なものから判定していくことになる。</p>
</section>
<section id="further-inheritance">
<h3>Further inheritance<a class="headerlink" href="#further-inheritance" title="Permalink to this heading">¶</a></h3>
<p><code class="docutils literal notranslate"><span class="pre">ValidationError</span></code> は汎用エラーとして、もっと特殊なエラーを定義することにする。そのようなエラーを <code class="docutils literal notranslate"><span class="pre">ValidationError</span></code> から継承して定義する。</p>
<ul class="simple">
<li><p>基底クラスのコンストラクターでの <code class="docutils literal notranslate"><span class="pre">this.name</span></code> のセットにコツがある。</p></li>
</ul>
</section>
<section id="wrapping-exceptions">
<h3>Wrapping exceptions<a class="headerlink" href="#wrapping-exceptions" title="Permalink to this heading">¶</a></h3>
<p>今度は関数 <code class="docutils literal notranslate"><span class="pre">readUser(json)</span></code> が送出するエラーを <code class="docutils literal notranslate"><span class="pre">ReadError</span></code> に一本化する。関数内部に設けてある <code class="docutils literal notranslate"><span class="pre">try</span></code> 節から何らかのエラーが送出された場合、<code class="docutils literal notranslate"><span class="pre">catch</span></code> 節でそのエラーオブジェクトをこの新しいエラー型オブジェクトに持たせる。それから、この新しいエラーオブジェクトを送出して終わる。</p>
<p>この節のエラー処理に関する議論は美しい。本文のクラスを図式化するとこういう感じになる：</p>
<div class="mermaid">
            classDiagram
    direction TB

    Error &lt;|-- ValidationError
    Error &lt;|-- SyntaxError
    ValidationError &lt;|-- PropertyRequiredError
    Error &lt;|-- ReadError
    Error &lt;--o ReadError : cause

    class Error{
        +string message
        +string name
    }

    class PropertyRequiredError{
        +string property
    }

    class ReadError{
    }
        </div></section>
<section id="id1">
<h3>Tasks<a class="headerlink" href="#id1" title="Permalink to this heading">¶</a></h3>
<section id="inherit-from-syntaxerror">
<h4>Inherit from SyntaxError<a class="headerlink" href="#inherit-from-syntaxerror" title="Permalink to this heading">¶</a></h4>
<p>組み込みエラーから自作エラーを定義する作法を確認する問題。</p>
</section>
</section>
</section>
</section>


          </div>
              <div class="related bottom">
                &nbsp;
  <nav id="rellinks">
    <ul>
        <li>
          &larr;
          <a href="09-classes.html" title="Previous document">Classes</a>
        </li>
        <li>
          <a href="11-async.html" title="Next document">Promises, async/await</a>
          &rarr;
        </li>
    </ul>
  </nav>
              </div>
          
      </div>
      <div class="clearer"></div>
    </div>
<div class="footer">
  <ul>
    <li id="footer_logo">
      <a class="image-reference" href="https://showa-yojyo.github.io/" title="プレハブ小屋 Since 1999"><img src="../../_static/logos.png"/></a>
    </li>
    <li id="footer_copyright">
      Copyright &copy; 1999-2024, プレハブ小屋 All rights reserved.
    </li>
  </ul>
</div>
  </body>
</html>